### ISSUE TITLE
More informative error messages of ImageJ Macro node

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip-imagej2#10]
When using the ImageJ Macro node, it's not unusual that macros produce output images that differ in their dimensionality from the input. Particularly when working with RGB images (that will be seen as multi-channel hyperstacks) and converting them between different color spaces, an in-depth knowledge of ImageJ 1.x data structures is necessary to understand why certain processes are failing.

A more verbose error reporting would help here, e.g. reporting the dimensions of the current image after running the macro, and how it differs from the dimensions expected by the KNIME node.

See: https://github.com/knime-ip/knip-imagej2/blob/master/org.knime.knip.imagej1/src/org/knime/knip/imagej1/IJMacroNodeFactory.java#L279-L283

**Comment by dietzc** [comment]
can you attach a super small failing example which you expect to work? I could output more informative error messages of course, but I could also try to allow outputs of different sizes.

thanks for reporting! :-)

**Comment by dietzc** [comment]
will be solved with _https://github.com/knime-ip/knip-scripting/issues/74_
