### ISSUE TITLE
Add SCIFIO services to list of supported services

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip-imagej2#16]
In line with https://github.com/knime-ip/knip-imagej2/commit/f624fd4ca777c9a0e20142a5f51e56f6547fcffb, I suggest to support more SCIFIO-related services such as [`FormatService`](http://javadoc.imagej.net/SCIFIO/index.html?io/scif/services/FormatService.html) to allow things like [getting metadata from files](https://gist.github.com/ctrueden/8c14e07d5f2d9b4623b42b2e80feca30) (see this [gitter log](https://gitter.im/scifio/scifio?at=58b5af39fef1d2de52abbe96)).

Or did I miss an easy possibility of doing this?

**Comment by imagejan** [comment]
@dietzc is this possible in the short term? I'd like to avoid falling back to bio-formats, and directly use SCIFIOService if possible.

**Comment by dietzc** [comment]
Hm. I think we should allow _all_ services. I'll try it end of the week.

**Comment by imagejan** [comment]
I guess this was fixed with https://github.com/knime-ip/knip-imagej2/commit/4c6fd3cd413bbf3f442d814264916760064c9696 and can be closed.
