### ISSUE TITLE
Support CommandService

### ISSUE THREAD

**Issue by stelfrich** [knime-ip/knip-imagej2#31]
Along the lines of #16, we should also support `CommandService`. While this seems to open up Pandora's box, it's a necessity for developers to be able to write wrappers for their otherwise unsupported `Command`s.

In a quick test, things seem to be working without problems.

**Comment by imagejan** [comment]
As @dietzc suggested in https://github.com/knime-ip/knip-imagej2/issues/16#issuecomment-284898540, adding *all* `Service`s available at runtime would be great.

**Comment by gab1one** [comment]
@imagejan I put a version of knip/imagej-2 that does exactly this on the nightly build. Can you try out if it works for you?

**Comment by imagejan** [comment]
Thanks @gab1one! I'll only be able to test this after the NEUBIAS conference (Feb 5-8), so will try to report here in two weeks or so.
